export const VISIBILITY_OPTIONS = [
  {
    value: 'PUBLIC',
    label: 'Full Info Visible',
    tagline: 'Recommended for emergencies',
    description: 'Anyone who scans sees name, photo, blood group, allergies, conditions, medications, and all emergency contacts.',
    icon: '👁️',
    fields: [
      'Name & Photo',
      'Blood Group',
      'Allergies & Conditions',
      'Medications',
      'Doctor Info',
      'Emergency Contacts',
    ],
    fieldVisibility: [true, true, true, true, true, true],
  },
  {
    value: 'MINIMAL',
    label: 'Name & Contacts Only',
    tagline: 'Balanced privacy',
    description: 'Scanners see name, photo, and emergency contact buttons. Medical details stay hidden.',
    icon: '🛡️',
    fields: [
      'Name & Photo',
      'Blood Group',
      'Allergies & Conditions',
      'Medications',
      'Doctor Info',
      'Emergency Contacts',
    ],
    fieldVisibility: [true, false, false, false, false, true],
  },
  {
    value: 'HIDDEN',
    label: 'Hidden',
    tagline: 'Card shows nothing',
    description: 'Scanning shows only that this is a registered emergency card. No personal info is revealed.',
    icon: '🚫',
    fields: [
      'Name & Photo',
      'Blood Group',
      'Allergies & Conditions',
      'Medications',
      'Doctor Info',
      'Emergency Contacts',
    ],
    fieldVisibility: [false, false, false, false, false, false],
  },
];