import { StyleSheet, Platform } from 'react-native';
import { spacing } from '@/theme';

export const emergencyStyles = StyleSheet.create({
  // Header
  header: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: spacing.screenH, paddingTop: Platform.OS === 'ios' ? 10 : 16, paddingBottom: 14, borderBottomWidth: 1 },
  backBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', marginLeft: -6 },
  pageTitle: { fontSize: 20, fontWeight: '900', letterSpacing: -0.4 },
  pageSub: { fontSize: 12, marginTop: 2, lineHeight: 17, fontWeight: '500' },
  visPill: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 99, borderWidth: 1, flexShrink: 0 },
  visDot: { width: 5, height: 5, borderRadius: 2.5 },
  visTx: { fontSize: 11, fontWeight: '800', letterSpacing: 0.2 },
  scroll: { paddingHorizontal: spacing.screenH, paddingTop: 18, gap: 22 },
  sectionDesc: { fontSize: 12, fontWeight: '500', marginBottom: 10 },
  hiddenWarn: { flexDirection: 'row', alignItems: 'flex-start', gap: 13, borderRadius: 16, borderWidth: 1, padding: 16 },
  hiddenWarnIcon: { width: 38, height: 38, borderRadius: 11, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  hiddenWarnTitle: { fontSize: 14, fontWeight: '800', marginBottom: 4 },
  hiddenWarnBody: { fontSize: 13, opacity: 0.85, lineHeight: 18 },
  safetyNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 16, borderWidth: 1, padding: 15 },
  safetyIcon: { width: 30, height: 30, borderRadius: 9, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  safetyTx: { fontSize: 13, flex: 1, lineHeight: 19, fontWeight: '500', paddingTop: 4 },

  // PreviewDataRow
  prRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, paddingHorizontal: 16, paddingVertical: 10 },
  prIcon: { width: 28, height: 28, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 },
  prBody: { flex: 1, gap: 2 },
  prLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 0.6, textTransform: 'uppercase' },
  prValue: { fontSize: 14, fontWeight: '600', lineHeight: 19 },

  // ScannerPreview card
  pvCard: { borderRadius: 18, borderWidth: 1, overflow: 'hidden', ...Platform.select({ ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.18, shadowRadius: 20 }, android: { elevation: 8 } }) },
  pvTopBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  pvTopLeft: { gap: 3 },
  pvScanBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 5, borderWidth: 1, alignSelf: 'flex-start' },
  pvScanDot: { width: 5, height: 5, borderRadius: 2.5 },
  pvScanTx: { fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  pvCaption: { fontSize: 11, fontWeight: '500' },
  pvVisBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99, borderWidth: 1 },
  pvVisTx: { fontSize: 11, fontWeight: '800' },
  pvIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1 },
  pvAvatar: { width: 46, height: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, flexShrink: 0 },
  pvAvatarTx: { fontSize: 17, fontWeight: '900' },
  pvIdentityBody: { flex: 1, gap: 5 },
  pvName: { fontSize: 16, fontWeight: '800', letterSpacing: -0.2 },
  pvMetaChip: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 5, borderWidth: 1, alignSelf: 'flex-start' },
  pvMetaChipTx: { fontSize: 10.5, fontWeight: '600' },
  pvEmergencyPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, borderWidth: 1, flexShrink: 0 },
  pvEmergencyTx: { fontSize: 10, fontWeight: '800', letterSpacing: 0.2 },
  pvSection: { borderBottomWidth: 1 },
  pvSectionHead: { fontSize: 9.5, fontWeight: '800', letterSpacing: 1.2, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4 },
  pvContact: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12 },
  pvContactAv: { width: 36, height: 36, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  pvContactAvTx: { fontSize: 13, fontWeight: '900' },
  pvContactName: { fontSize: 14, fontWeight: '700' },
  pvContactRel: { fontSize: 11.5, marginTop: 2 },
  pvCallBtn: { width: 34, height: 34, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  pvBlocked: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 20 },
  pvBlockedIcon: { width: 44, height: 44, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  pvBlockedTitle: { fontSize: 14.5, fontWeight: '800' },
  pvBlockedSub: { fontSize: 12.5, marginTop: 3, lineHeight: 17 },
  pvFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderTopWidth: 1 },
  pvFooterTx: { fontSize: 10, fontWeight: '500' },

  // VisibilitySelector
  vsPillRow: { flexDirection: 'row', borderRadius: 14, borderWidth: 1, padding: 4, gap: 4 },
  vsPill: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: 'transparent' },
  vsPillTx: { fontSize: 12.5, fontWeight: '600' },
  vsDetail: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 12, borderWidth: 1, padding: 14 },
  vsDetailIconWrap: { width: 36, height: 36, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  vsDetailTitle: { fontSize: 13, fontWeight: '800', letterSpacing: 0.1, marginBottom: 3 },
  vsDetailBody: { fontSize: 12, lineHeight: 17, fontWeight: '500' },

  // FieldAccessTable
  ftTable: { borderRadius: 17, borderWidth: 1, overflow: 'hidden' },
  ftTableHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1 },
  ftTableHeadLbl: { fontSize: 9.5, fontWeight: '800', letterSpacing: 1.0 },
  ftCatDivider: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4, gap: 8, borderBottomWidth: 1 },
  ftCatTx: { fontSize: 9, fontWeight: '800', letterSpacing: 1.2 },
  ftCatLine: { flex: 1, height: 1 },
  ftRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 11, gap: 10 },
  ftRowDim: { opacity: 0.4 },
  ftDot: { width: 7, height: 7, borderRadius: 3.5, flexShrink: 0 },
  ftFieldLabel: { fontSize: 14, fontWeight: '600' },
  ftFieldSub: { fontSize: 11, marginTop: 1, fontStyle: 'italic' },
  ftLockedTag: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, borderWidth: 1 },
  ftLockedTx: { fontSize: 9.5, fontWeight: '600' },

  // StickyFooter
  sfBar: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.screenH, paddingTop: 14, paddingBottom: Platform.OS === 'ios' ? 34 : 18, borderTopWidth: 1, ...Platform.select({ ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.08, shadowRadius: 12 }, android: { elevation: 12 } }) },
  sfLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sfDot: { width: 7, height: 7, borderRadius: 3.5 },
  sfTx: { fontSize: 13.5, fontWeight: '600' },
  sfBtn: { borderRadius: 11, paddingHorizontal: 22, paddingVertical: 11, alignItems: 'center', justifyContent: 'center', minWidth: 80 },
  sfBtnTx: { fontSize: 13.5, fontWeight: '800', color: '#fff' },
});