// src/styles/qr.style.js
import { Platform, StyleSheet } from "react-native";

export const qrStyles = StyleSheet.create({
  scroll: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "ios" ? 12 : 18,
    paddingBottom: 56,
    gap: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  pageTitle: { fontSize: 23, fontWeight: "900", letterSpacing: -0.5 },
  pageSub: { fontSize: 13, marginTop: 3, fontWeight: "500" },
  shareBtn: {
    width: 40,
    height: 40,
    borderRadius: 13,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 99,
    borderWidth: 1,
  },
  statusPillTx: { fontSize: 12, fontWeight: "800", letterSpacing: 0.1 },
  statusDesc: { fontSize: 12.5, flex: 1, fontWeight: "500" },
  dragHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: -4,
  },
  dragHintTx: { fontSize: 11, fontWeight: "500" },
  section: { gap: 10 },
  sectionHead: { fontSize: 10.5, fontWeight: "800", letterSpacing: 1.1 },
  actionList: { gap: 10 },
  revokedNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
  },
  revokedNoticeTx: { fontSize: 13.5, flex: 1, lineHeight: 20 },
  detailsBlock: { borderRadius: 17, borderWidth: 1, overflow: "hidden" },
  safetyTip: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 13,
    borderRadius: 16,
    borderWidth: 1,
    padding: 15,
  },
  safetyIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  safetyTx: {
    fontSize: 13,
    flex: 1,
    lineHeight: 19,
    fontWeight: "500",
    paddingTop: 5,
  },
  glossary: {
    borderRadius: 17,
    borderWidth: 1,
    overflow: "hidden",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  glossaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  glossaryDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginTop: 5.5,
    flexShrink: 0,
  },
  glossaryLabel: { fontSize: 13, fontWeight: "800", width: 105, flexShrink: 0 },
  glossaryDesc: { fontSize: 12.5, flex: 1, lineHeight: 18 },
});
