// src/styles/updates.style.js
import { spacing } from "@/theme";
import { StyleSheet } from "react-native";

export const updatesStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.screenH,
    paddingTop: spacing[5],
    paddingBottom: spacing[3],
    borderBottomWidth: 1,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
    flex: 1,
    textAlign: "center",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeDot: { width: 5, height: 5, borderRadius: 3 },
  badgeText: { fontSize: 11, fontWeight: "700" },
  scroll: {
    paddingHorizontal: spacing.screenH,
    paddingTop: 14,
    gap: 14,
    paddingBottom: 30,
  },
  stepContent: { gap: 14 },
  note: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  noteText: { fontSize: 11.5, flex: 1, lineHeight: 17 },
  callInfoBox: { borderRadius: 14, borderWidth: 1, padding: 16, gap: 10 },
  callInfoTitle: { fontSize: 13, fontWeight: "700" },
  callInfoRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  callInfoDot: { width: 7, height: 7, borderRadius: 4, flexShrink: 0 },
  callInfoText: { fontSize: 12.5, flex: 1 },
  callInfoDivider: { height: 1, marginVertical: 2 },
  callInfoNote: { fontSize: 11.5, lineHeight: 17 },
  emptyContacts: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 32,
    alignItems: "center",
    gap: 10,
  },
  emptyTitle: { fontSize: 15, fontWeight: "700" },
  emptySub: { fontSize: 12.5, textAlign: "center", lineHeight: 18 },
  emptyAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 4,
  },
  emptyAddBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
  },
  addBtnIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnLabel: { fontSize: 14, fontWeight: "700" },
  addBtnSub: { fontSize: 11.5, marginTop: 2 },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  reviewAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  reviewAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#fff",
    flexShrink: 0,
  },
  reviewAvatarText: { fontSize: 20, fontWeight: "900" },
  reviewName: { fontSize: 16, fontWeight: "800", letterSpacing: -0.2 },
  reviewClass: { fontSize: 12, marginTop: 2 },
  reviewStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reviewStatusDot: { width: 5, height: 5, borderRadius: 3 },
  reviewStatusText: { fontSize: 11, fontWeight: "700" },
  reviewWarn: { borderRadius: 10, borderWidth: 1, padding: 12 },
  reviewWarnText: { fontSize: 12.5, lineHeight: 18, fontWeight: "600" },
});
