import { C } from "@/constants/constants";
import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  glowTop: {
    position: "absolute",
    top: -80,
    alignSelf: "center",
    width: 380,
    height: 380,
    borderRadius: 190,
    backgroundColor: C.red,
    opacity: 0.065,
  },
  glowBottom: {
    position: "absolute",
    bottom: 20,
    left: -90,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: C.red,
    opacity: 0.04,
  },
  glowRight: {
    position: "absolute",
    top: "35%",
    right: -80,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: C.red,
    opacity: 0.035,
  },
  topSection: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 24,
    justifyContent: "center",
    gap: 4,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  brandBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: C.redGlow,
    borderWidth: 1,
    borderColor: C.borderRed,
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  brandBadgeDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.red,
  },
  brandBadgeText: {
    color: C.red,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 2.8,
  },
  brandDivider: { width: 1, height: 11, backgroundColor: C.white15 },
  brandTagline: {
    color: C.white35,
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.4,
  },
  versionTag: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 2,
  },
  versionText: {
    color: "rgba(255,255,255,0.22)",
    fontSize: 8,
    fontWeight: "600",
    letterSpacing: 1,
  },
  heroArea: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginBottom: 4,
  },
  ring: { position: "absolute", borderColor: "rgba(255,59,48,0.16)" },
  iconWrapper: { position: "relative" },
  iconGlowRing: {
    position: "absolute",
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "rgba(255,59,48,0.12)",
  },
  iconCard: {
    overflow: "hidden",
    shadowColor: C.red,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.5,
    shadowRadius: 28,
    elevation: 24,
    borderWidth: 1,
    borderColor: C.borderRed,
  },
  iconCardInner: { flex: 1, alignItems: "center", justifyContent: "center" },
  iconCardHighlight: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  iconCardBottomSheen: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 32,
    backgroundColor: "rgba(255,59,48,0.04)",
  },
  statusDot: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 11,
    height: 11,
    borderRadius: 5.5,
    backgroundColor: C.green,
    shadowColor: C.green,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 7,
    elevation: 6,
    borderWidth: 2,
    borderColor: C.bg,
  },
  orbitAnchor: {
    position: "absolute",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  orbitDot: {
    position: "absolute",
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,59,48,0.55)",
    shadowColor: C.red,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
  },
  floatingBadge: {
    position: "absolute",
    backgroundColor: "rgba(18,14,14,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 9,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
  },
  floatingBadgeLeft: { left: 10, top: "32%" },
  floatingBadgeRight: { right: 10, top: "46%" },
  floatingBadgeNum: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: Platform.select({ ios: "800", android: "700" }),
    letterSpacing: -0.4,
  },
  floatingBadgeLabel: {
    color: C.white35,
    fontSize: 9,
    fontWeight: "600",
    marginTop: 2,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  floatingBadgeBar: {
    width: 20,
    height: 2,
    borderRadius: 1,
    backgroundColor: C.red,
    marginTop: 6,
    opacity: 0.7,
  },
  floatingBadgeLiveWrap: { flexDirection: "row", alignItems: "center", gap: 5 },
  floatingBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.green,
    shadowColor: C.green,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  floatingBadgeLive: {
    color: C.green,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  floatingBadgeSubtext: {
    color: "rgba(255,255,255,0.28)",
    fontSize: 8,
    fontWeight: "500",
    marginTop: 3,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  dataReadout: {
    position: "absolute",
    bottom: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dataReadoutDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.green,
    shadowColor: C.green,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  dataReadoutText: {
    color: "rgba(255,255,255,0.22)",
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 2.2,
  },
  titleBlock: { alignItems: "center" },
  titleEyebrow: {
    color: "rgba(255,255,255,0.28)",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 5,
    marginBottom: 4,
  },
  titleRow: { flexDirection: "row", alignItems: "baseline" },
  titleMain: {
    fontWeight: Platform.select({ ios: "800", android: "700" }),
    color: C.white,
    letterSpacing: -1.8,
  },
  titleAccent: {
    color: C.red,
    fontWeight: Platform.select({ ios: "800", android: "700" }),
    letterSpacing: -1.8,
  },
  titleSubRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
  },
  titleSubDash: {
    width: 18,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  titleSub: {
    fontSize: 11,
    fontWeight: "500",
    color: "rgba(255,255,255,0.30)",
    letterSpacing: 3.2,
    textTransform: "uppercase",
  },
  bottomSection: { paddingHorizontal: 20, gap: 12 },
  dividerRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  dividerText: {
    color: "rgba(255,255,255,0.30)",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.4,
  },
  featureRow: {
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    flexWrap: "wrap",
  },
  featurePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  featurePillIcon: { opacity: 0.75 },
  featurePillText: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 10,
    fontWeight: "500",
  },
  buttonGroup: { gap: 8 },
  primaryWrapper: {
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: C.red,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 18,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: 14,
    gap: 8,
  },
  primaryLabel: {
    color: C.white,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  primaryArrow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.22)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  secondaryButton: { paddingVertical: 12, alignItems: "center" },
  secondaryLabel: {
    color: "rgba(255,255,255,0.30)",
    fontSize: 13,
    fontWeight: "500",
  },
  secondaryLabelAccent: {
    color: "rgba(255,255,255,0.62)",
    fontWeight: "700",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(255,255,255,0.25)",
  },
  trustRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingBottom: 2,
  },
  trustDotWrap: {
    width: 10,
    height: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  trustDotOuter: {
    position: "absolute",
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: C.greenGlow,
  },
  trustDotInner: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: C.green,
  },
  trustText: {
    color: "rgba(255,255,255,0.25)",
    fontSize: 11,
    letterSpacing: 0.2,
  },
  breathGlow: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: C.red,
  },
  scanLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1.5,
    borderRadius: 1,
    backgroundColor: C.red,
    shadowColor: C.red,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 7,
    elevation: 6,
  },
  shimmer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 52,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 4,
  },
  shimmerThin: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 22,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 4,
  },
});
